[2024-11-02T02:47:56.595+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-11-02T02:47:56.613+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: predictive_maintenance_pipeline.train_best_model_bin manual__2024-11-02T02:47:38.261658+00:00 [queued]>
[2024-11-02T02:47:56.623+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: predictive_maintenance_pipeline.train_best_model_bin manual__2024-11-02T02:47:38.261658+00:00 [queued]>
[2024-11-02T02:47:56.623+0000] {taskinstance.py:2865} INFO - Starting attempt 1 of 1
[2024-11-02T02:47:56.638+0000] {taskinstance.py:2888} INFO - Executing <Task(PythonOperator): train_best_model_bin> on 2024-11-02 02:47:38.261658+00:00
[2024-11-02T02:47:56.647+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=193) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-11-02T02:47:56.648+0000] {standard_task_runner.py:72} INFO - Started process 194 to run task
[2024-11-02T02:47:56.648+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'predictive_maintenance_pipeline', 'train_best_model_bin', 'manual__2024-11-02T02:47:38.261658+00:00', '--job-id', '36', '--raw', '--subdir', 'DAGS_FOLDER/mlops_version_py.py', '--cfg-path', '/tmp/tmpkgnbv0nu']
[2024-11-02T02:47:56.649+0000] {standard_task_runner.py:105} INFO - Job 36: Subtask train_best_model_bin
[2024-11-02T02:47:56.702+0000] {task_command.py:467} INFO - Running <TaskInstance: predictive_maintenance_pipeline.train_best_model_bin manual__2024-11-02T02:47:38.261658+00:00 [running]> on host 1dda86545537
[2024-11-02T02:47:56.801+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='predictive_maintenance_pipeline' AIRFLOW_CTX_TASK_ID='train_best_model_bin' AIRFLOW_CTX_EXECUTION_DATE='2024-11-02T02:47:38.261658+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-11-02T02:47:38.261658+00:00'
[2024-11-02T02:47:56.801+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-11-02T02:47:57.966+0000] {logging_mixin.py:190} INFO - Searching best binary model
[2024-11-02T02:47:57.970+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:47:58.146+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:47:58.307+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:47:58.486+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/joblib/parallel.py:1359: UserWarning: Loky-backed parallel loops cannot be called in a multiprocessing, setting n_jobs=1
  n_jobs = self._backend.configure(n_jobs=self.n_jobs, parallel=self,

[2024-11-02T02:48:01.789+0000] {logging_mixin.py:190} INFO - Best model found: RandomForestClassifier(class_weight={0: 0.697901, 1: 11.955361})
[2024-11-02T02:48:03.141+0000] {logging_mixin.py:190} INFO - Model trained and saved
[2024-11-02T02:48:03.142+0000] {python.py:240} INFO - Done. Returned value was: None
[2024-11-02T02:48:03.154+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-11-02T02:48:03.154+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=predictive_maintenance_pipeline, task_id=train_best_model_bin, run_id=manual__2024-11-02T02:47:38.261658+00:00, execution_date=20241102T024738, start_date=20241102T024756, end_date=20241102T024803
[2024-11-02T02:48:03.221+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2024-11-02T02:48:03.247+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-11-02T02:48:03.251+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
